---
- name: Pull docker image from dockerhub
  hosts: all
#  tasks:
#    - name: sudo Start docker service
#      service:
#        name: docker
#        state: started
#
#    - name: Pull docker image
#      shell: docker pull utkarsh67/dockerimage_calminipro
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: utkarsh67/dockerimage_calminipro
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: utkarshCal
        image: utkarsh67/dockerimage_calminipro
        state: started
        tty: yes
        interactive: yes