---
- name: Pull docker image from dockerhub
  hosts: all
  tasks:
    - name: sudo Start docker service
      service:
        name: docker
        state: started

    - name: Pull docker image
      shell: docker pull utkarsh67/dockerimage_calminipro

    - name: running container
      shell: docker run -it --name utkarshCal utkarsh67/dockerimage_calminipro:latest